/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedLixeiraRouteImport } from './routes/_authenticated/lixeira'
import { Route as AuthenticatedIaClientesRouteImport } from './routes/_authenticated/ia-clientes'
import { Route as AuthenticatedFormulariosRouteImport } from './routes/_authenticated/formularios'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAplicativosRouteImport } from './routes/_authenticated/aplicativos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLixeiraRoute = AuthenticatedLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaClientesRoute = AuthenticatedIaClientesRouteImport.update({
  id: '/ia-clientes',
  path: '/ia-clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormulariosRoute =
  AuthenticatedFormulariosRouteImport.update({
    id: '/formularios',
    path: '/formularios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAplicativosRoute =
  AuthenticatedAplicativosRouteImport.update({
    id: '/aplicativos',
    path: '/aplicativos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/aplicativos': typeof AuthenticatedAplicativosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/ia-clientes': typeof AuthenticatedIaClientesRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/aplicativos': typeof AuthenticatedAplicativosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/ia-clientes': typeof AuthenticatedIaClientesRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/aplicativos': typeof AuthenticatedAplicativosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/formularios': typeof AuthenticatedFormulariosRoute
  '/_authenticated/ia-clientes': typeof AuthenticatedIaClientesRoute
  '/_authenticated/lixeira': typeof AuthenticatedLixeiraRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/aplicativos'
    | '/configuracoes'
    | '/contratos'
    | '/crm'
    | '/cronograma'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/formularios'
    | '/ia-clientes'
    | '/lixeira'
    | '/servicos'
    | '/clientes/$id'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/aplicativos'
    | '/configuracoes'
    | '/contratos'
    | '/crm'
    | '/cronograma'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/formularios'
    | '/ia-clientes'
    | '/lixeira'
    | '/servicos'
    | '/clientes/$id'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/agenda'
    | '/_authenticated/aplicativos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contratos'
    | '/_authenticated/crm'
    | '/_authenticated/cronograma'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/formularios'
    | '/_authenticated/ia-clientes'
    | '/_authenticated/lixeira'
    | '/_authenticated/servicos'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lixeira': {
      id: '/_authenticated/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AuthenticatedLixeiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia-clientes': {
      id: '/_authenticated/ia-clientes'
      path: '/ia-clientes'
      fullPath: '/ia-clientes'
      preLoaderRoute: typeof AuthenticatedIaClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formularios': {
      id: '/_authenticated/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof AuthenticatedFormulariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aplicativos': {
      id: '/_authenticated/aplicativos'
      path: '/aplicativos'
      fullPath: '/aplicativos'
      preLoaderRoute: typeof AuthenticatedAplicativosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAplicativosRoute: typeof AuthenticatedAplicativosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFormulariosRoute: typeof AuthenticatedFormulariosRoute
  AuthenticatedIaClientesRoute: typeof AuthenticatedIaClientesRoute
  AuthenticatedLixeiraRoute: typeof AuthenticatedLixeiraRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAplicativosRoute: AuthenticatedAplicativosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFormulariosRoute: AuthenticatedFormulariosRoute,
  AuthenticatedIaClientesRoute: AuthenticatedIaClientesRoute,
  AuthenticatedLixeiraRoute: AuthenticatedLixeiraRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
